{% set version = "0.9.10" %}

package:
  name: xonsh
  version: {{ version }}

source:
  fn: xonsh-{{ version }}.tar.gz
  url: https://github.com/xonsh/xonsh/releases/download/{{ version }}/xonsh-{{ version }}.tar.gz
  sha256: d41fca7bef961121b2da9c31505e654c2312a7221b810ad6fd3b8c2eebeda3b7

build:
  script: python setup.py install --single-version-externally-managed --record=record.txt  # [not win]
  entry_points:
    - xonsh = xonsh.main:main
    - xonsh-cat = xonsh.xoreutils.cat:cat_main
  skip: True  # [py2k]
  number: 0

requirements:
  build:
    - python
    - setuptools
    - jupyter_client
  run:
    - python
    - prompt_toolkit
    - pygments >=2.2
    - setproctitle
    - pyreadline  # [win]

test:
  requires:
    - pytest
  imports:
    - xonsh
  commands:
    - USER=test xonsh -h  # [unix]
    - xonsh -h  # [win]


about:
  home: http://xon.sh
  license: BSD 2-Clause
  license_family: BSD
  license_file: license
  summary: Python-powered, cross-platform, Unix-gazing shell
  description: |
    Xonsh is a Python-powered, cross-platform, Unix-gazing shell shell language
    and command prompt. The language is a superset of Python 3.4+ with additional
    shell primitives that you are used to from Bash and IPython. It works on all
    major systems including Linux, Mac OSX, and Windows. Xonsh is meant for the
    daily use of experts and novices alike.
  doc_url: http://xon.sh
  dev_url: https://github.com/xonsh/xonsh

extra:
  recipe-maintainers:
    - scopatz
    - ocefpaf
    - melund
    - gforsyth
    - mitnk
