{% set version = "0.2.7" %}

package:
  name: xonsh
  version: {{ version }}

source:
  fn: xonsh-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/x/xonsh/xonsh-{{ version }}.tar.gz
  md5: b810500337fb43b21a03146cdf30d6b5

build:
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - xonsh = xonsh.main:main
  skip: True  # [py2k]
  number: 0

requirements:
  build:
    - python
    - ply
    - setuptools
    - jupyter
  run:
    - python
    - ply
    - prompt_toolkit  # [win]
    - setproctitle

test:
  requires:
    - nose
  imports:
    - xonsh
  commands:
    - xonsh -h

app:
  entry: xonsh
  icon: xonsh.png

about:
  home: http://xonsh.org/
  license: BSD
  summary: xonsh is a Python-ish, BASHwards-facing shell.
  
extra:
  recipe-maintainers:
    - scopatz
    - ocefpaf
    - melund
